# Generated by Django 5.0.4 on 2024-04-23 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('balancesheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('entry_type', models.CharField(choices=[('C', 'Credited'), ('D', 'Debited')], default='D', max_length=3)),
                ('category', models.CharField(choices=[('ENT', 'Entertainment'), ('GRO', 'Groceries'), ('TRA', 'Transport'), ('FO', 'Food')], default='FO', max_length=3)),
                ('sheet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balancesheet.balancesheets', verbose_name='sheet_id')),
            ],
        ),
    ]
