# Generated by Django 5.0.4 on 2024-04-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="<django.db.models.query_utils.DeferredAttribute object at 0x106510910>'s Balancesheet", max_length=30, verbose_name='Balancesheet name')),
            ],
        ),
    ]
