# Generated by Django 5.0.4 on 2024-04-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='provider',
            field=models.CharField(choices=[('G', 'Google'), ('E', 'Email')], default='E', max_length=2, verbose_name='Provider'),
        ),
    ]
